[package]
name = "shuten_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuten = { version = "0.1.0", path = "../shuten" }
slotmap = "1.0.7"
